######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 21 14:55:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h mainwindow.h readthread.h
FORMS += mainwindow.ui
SOURCES += client.cpp main.cpp mainwindow.cpp readthread.cpp
