######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 20 23:19:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += includes.h server.h wrappers.h
SOURCES += server.c serverMain.c wrappers.c
